/** Sample subjects parsed from SIAS schedule (dev preview). */
window.PUPSYNC_MOCK_SUBJECTS = [
  {
    subjectCode: 'COMP 009',
    description: 'Object Oriented Programming',
    lectureHours: '2.0',
    labHours: '3.0',
    units: '3.0',
    section: '1N - BSIT 2-1N',
    days: ['Saturday', 'Sunday'],
    lectureTime: { start: '07:30', end: '10:30' },
    labTime: { start: '10:30', end: '12:30' },
    faculty: 'REDIS, JR., SEVERINO',
    excluded: false,
    parseError: null
  },
  {
    subjectCode: 'COMP 010',
    description: 'Information Management',
    lectureHours: '2.0',
    labHours: '3.0',
    units: '3.0',
    section: '1N - BSIT 2-1N',
    days: ['Tuesday', 'Friday'],
    lectureTime: { start: '16:30', end: '18:30' },
    labTime: { start: '16:30', end: '19:30' },
    faculty: 'FACULTY, SAMPLE',
    excluded: false,
    parseError: null
  },
  {
    subjectCode: 'COMP 012',
    description: 'Network Administration',
    lectureHours: '2.0',
    labHours: '3.0',
    units: '3.0',
    section: '1N - BSIT 2-1N',
    days: ['Tuesday', 'Friday'],
    lectureTime: { start: '13:30', end: '15:30' },
    labTime: { start: '13:30', end: '16:30' },
    faculty: 'FACULTY, SAMPLE',
    excluded: false,
    parseError: null
  },
  {
    subjectCode: 'COMP 013',
    description: 'Human Computer Interaction',
    lectureHours: '3.0',
    labHours: '0.0',
    units: '3.0',
    section: '1N - BSIT 2-1N',
    days: ['Monday'],
    lectureTime: { start: '18:00', end: '21:00' },
    labTime: null,
    faculty: 'FACULTY, SAMPLE',
    excluded: false,
    parseError: null
  },
  {
    subjectCode: 'COMP 014',
    description: 'Quantitative Methods with Modeling and Simulation',
    lectureHours: '3.0',
    labHours: '0.0',
    units: '3.0',
    section: '1N - BSIT 2-1N',
    days: ['Thursday'],
    lectureTime: { start: '18:00', end: '21:00' },
    labTime: null,
    faculty: 'FACULTY, SAMPLE',
    excluded: false,
    parseError: null
  },
  {
    subjectCode: 'INTE 202',
    description: 'Integrative Programming and Technologies 1',
    lectureHours: '2.0',
    labHours: '3.0',
    units: '3.0',
    section: '1N - BSIT 2-1N',
    days: ['Monday', 'Thursday'],
    lectureTime: { start: '13:30', end: '16:30' },
    labTime: { start: '13:30', end: '15:30' },
    faculty: 'NAYRE, RACHEL',
    excluded: false,
    parseError: null
  },
  {
    subjectCode: 'PATHFIT 4',
    description: 'Physical Activity Towards Health and Fitness 4',
    lectureHours: '2.0',
    labHours: '0.0',
    units: '2.0',
    section: '1N - BSIT 2-1N',
    days: ['Monday'],
    lectureTime: { start: '09:00', end: '11:00' },
    labTime: null,
    faculty: 'FACULTY, SAMPLE',
    excluded: false,
    parseError: null
  },
  {
    subjectCode: 'STAT 023',
    description: 'Probability and Statistics for CS/IT Students',
    lectureHours: '3.0',
    labHours: '0.0',
    units: '3.0',
    section: '1N - BSIT 2-1N',
    days: ['Saturday'],
    lectureTime: { start: '13:30', end: '16:30' },
    labTime: null,
    faculty: 'FACULTY, SAMPLE',
    excluded: false,
    parseError: null
  }
];
